### ISSUE TITLE
Quest: Frankly, It Makes No Sense

### ISSUE THREAD

**Issue by Bearrman** [Looking4Group/L4G_Core#3718] opened 2017-05-08 12:47 UTC
Nothing happens when you click the Arcano control units

**Comment by tst12** [comment] 2017-05-08 12:58
https://github.com/Looking4Group/L4G_Core/issues/2910
https://github.com/Looking4Group/L4G_Core/pull/3549

**Comment by Saltgurka** [comment] 2017-05-08 13:38
Duplicate of: https://github.com/Looking4Group/L4G_Core/issues/2910
Proposed fix: https://github.com/Looking4Group/L4G_Core/pull/3549

**Closed by Saltgurka** 2017-05-08 13:38 UTC

**Comment by AnonXS** [comment] 2017-05-08 13:41
Dublicate https://github.com/Looking4Group/L4G_Core/issues/2910
