### ISSUE TITLE
Gauging the Resonant Frequency

### ISSUE THREAD

**Issue by gnarwi** [Looking4Group/L4G_Core#3581] opened 2017-04-23 10:07 UTC
quest cant be done. scanners dont create rifts or beams to each other.

**Comment by tst12** [comment] 2017-04-23 10:10
https://github.com/Looking4Group/L4G_Core/pull/3573

**Comment by tst12** [comment] 2017-04-23 10:12
https://github.com/Looking4Group/L4G_Core/issues/2003

**Comment by Saltgurka** [comment] 2017-04-23 10:21
Duplicate of https://github.com/Looking4Group/L4G_Core/issues/2003

Solved in https://github.com/Looking4Group/L4G_Core/pull/3573

**Closed by Saltgurka** 2017-04-23 10:21 UTC
