### ISSUE TITLE
Last boss in BF bugged

### ISSUE THREAD

**Issue by grimmur** [Looking4Group/L4G_Core#3076] opened 2016-12-10 01:09 UTC
The last boss in BF hcs got bugged :( invalid target. 
![bf bug](https://cloud.githubusercontent.com/assets/24377505/21069801/4e6295f2-be75-11e6-94dd-755e185d7046.png)

**Comment by Saltgurka** [comment] 2016-12-31 23:24
Insufficient information to reproduce the issue. Closing.

**Comment by Saltgurka** [comment] 2017-01-08 01:42
After some investigation and with the help of some nice players we figured out that the reason this happens is when the summoners are killed too far away from Keli'dan.

This is fixed with https://github.com/Looking4Group/L4G_Core/pull/3118

**Comment by AnonXS** [comment] 2017-02-19 17:12
Distance set might be too low. Bug reoccoured.

**Comment by Saltgurka** [comment] 2017-02-23 23:16
Increased to 140 https://github.com/Looking4Group/L4G_Core/commit/529282dfad3bdbd0dd5d443c5d95e31ee79b90d8

**Closed by Saltgurka** 2017-02-23 23:16 UTC
Labels: Dev.Report.Incomplete/Invalid
