### ISSUE TITLE
Bloodgem Crystals

### ISSUE THREAD

**Issue by Durstt** [Looking4Group/L4G_Core#3631] opened 2017-04-29 05:48 UTC
The Quest Bloodgem Crystals is bugged, it  targets a smaller red crystal instead of the bigger one and doesn't siphon the crystal.

**Comment by Saltgurka** [comment] 2017-04-29 12:42
https://github.com/Looking4Group/L4G_Core/issues/3354
https://github.com/Looking4Group/L4G_Core/issues/2173
https://github.com/Looking4Group/L4G_Core/issues/2009
https://github.com/Looking4Group/L4G_Core/issues/1555
https://github.com/Looking4Group/L4G_Core/issues/1361

Duplicate of https://github.com/Looking4Group/L4G_Core/issues/2795

**Closed by Saltgurka** 2017-04-29 12:42 UTC
