### ISSUE TITLE
Incandescent Fel Spark drops Mote of Shadow instead of Mote of Fire

### ISSUE THREAD

**Issue by pesky89** [Looking4Group/L4G_Core#3664] opened 2017-05-02 16:09 UTC
Incandescent Fel Spark mobs should have 38% chance of dropping 1-2 Mote of Fire.
Instead, the mobs drop Mote of Shadow

http://www.wowhead.com/npc=22323/incandescent-fel-spark

**Comment by tst12** [comment] 2017-05-02 16:17
it is difficult to use the search https://github.com/Looking4Group/L4G_Core/issues?utf8=%E2%9C%93&q=Fel%20Spark

**Comment by Saltgurka** [comment] 2017-05-02 16:58
They dropped Mote of Shadow pre 2.1.0. We are currently on patch 2.0.0.

Duplicate of https://github.com/Looking4Group/L4G_Core/issues/3424

**Closed by Saltgurka** 2017-05-02 16:58 UTC
