### ISSUE TITLE
I finish my redemption quest and dont get the spell

### ISSUE THREAD

**Issue by perenhas** [Looking4Group/L4G_Core#3787] opened 2017-05-20 20:49 UTC
I do the quest but i not get the spell, and another quest i defend the farm and when i go finish the quest npc just die

**Comment by AnonXS** [comment] 2017-05-23 07:23
http://db.hellfire-tbc.com/?quest=10366, http://db.hellfire-tbc.com/?quest=1646, http://db.hellfire-tbc.com/?quest=2997, http://db.hellfire-tbc.com/?quest=1642, http://db.hellfire-tbc.com/?quest=2998

**Comment by perenhas** [comment] 2017-05-23 14:39
i ress Faulk but hes not give the nexte quest

2017-05-23 3:23 GMT-04:00 AnonXS <notifications@github.com>:

**Comment by Saltgurka** [comment] 2017-05-23 22:40
Create an ingame ticket to request a new Symbol of Life. That will allow you to resurrect the NPC again and accept his quest.

Duplicate of https://github.com/Looking4Group/L4G_Core/issues/3533

**Closed by Saltgurka** 2017-05-23 22:40 UTC
