### ISSUE TITLE
bloodgem crystals 

### ISSUE THREAD

**Issue by Taniku** [Looking4Group/L4G_Core#3354] opened 2017-04-06 18:20 UTC
i dosen't work
when you use the bloodgem you dont finish the quest

**Comment by Saltgurka** [comment] 2017-04-06 18:52
Quest works, but you need to face directly towards the crystal, otherwise the spell is interrupted. Auto-facing is for some reason not working for this spell.
Gathering a few of the crystals and using them one after another without moving in between will let you complete the quest.

Duplicate of #2795

**Closed by Saltgurka** 2017-04-06 18:52 UTC
