### ISSUE TITLE
Quest Broken / Bloodgem Crystals(10204)

### ISSUE THREAD

**Issue by herodope** [Looking4Group/L4G_Core#3334] opened 2017-04-05 06:41 UTC
Quest Name: Bloodgem Crystals(10204)
Quest ID: 10204
Quest Item ID: 28452

When attempting to do the quest, I noticed the droprate is fairly low. When you do finally get a crystal(28452), it channels for a brief moment, then cancels itself. This is easily reproduceable, and makes the quest unable to complete. A guildmate who was in the area also had the exact same problem with 3 seperate crystals, and I tried twice.

**Comment by AnonXS** [comment] 2017-04-05 17:38
https://github.com/Looking4Group/L4G_Core/issues/2173
https://github.com/Looking4Group/L4G_Core/issues/1555
https://github.com/Looking4Group/L4G_Core/issues/2009
https://github.com/Looking4Group/L4G_Core/issues/1361

**Comment by Saltgurka** [comment] 2017-04-05 19:58
Quest works, but you need to face directly towards the crystal, otherwise the spell is interrupted. Auto-facing is for some reason not working for this spell.

Duplicate of https://github.com/Looking4Group/L4G_Core/issues/2795

**Closed by Saltgurka** 2017-04-05 19:58 UTC
