### ISSUE TITLE
Stoneclaw Totem

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#652] opened 2016-04-22 22:50 UTC
Originally reported by: **Anonymous**

---

Stoneclaw Totem is only taunting enemys at 1 second left of its duration instead of its full 8 second duration.

---
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/656

**Comment by Saltgurka** [comment] 2016-11-30 11:21
https://bitbucket.org/Xadras/tbcpvp/commits/3212a556f793116a5ed4e29b383885f2041e3205

**Comment by Saltgurka** [comment] 2016-12-01 00:58
Looking at this video, altough it's not TBC makes me think Stoneclaw should not pulse on drop down: https://www.youtube.com/watch?v=iza7g4z2h00

I also looked at the totems that are instant cast in TBCPvP and all listed in the commit above seem to already be instant in our core as well. I have no idea where it's handled, but it seems to work.

As for the totem itself, it seems to work just fine. I can't reproduce the issue where it only taunts at the last second. For me it pulses during the whole duration.

Closing this issue since it is specifically regarding Stoneclaw Totem, which is working as intended. Reopen if new proof is found

**Closed by Saltgurka** 2016-12-01 00:58 UTC
Labels: Class.Shaman, Core.Spell, Dev.Report.Complete/Valid
