### ISSUE TITLE
TK/Al'ar - Phase 2 adds should deal damage to Al'ar

### ISSUE THREAD

**Issue by Woomz** [Looking4Group/L4G_Core#2922] opened 2016-10-16 18:50 UTC
Hey there,

if you kill the adds of Al'ar, he should actually get 2% of his overall life as damage. This doesnt work.

**Comment by Xadras** [comment] 2016-10-16 19:01
As far as i know this feature was added later

**Comment by honeyhoney** [comment] 2016-10-16 19:01
Could you provide a source for those values? Preferably an early kill video (think: world first) with timestamps?

**Comment by Woomz** [comment] 2016-10-16 20:56
Okay, so you're saying you implemented it prenerv - the 3% (it's actually 3) was added with Patch 2.1:

The Al'ar encounter has been significantly reworked. Her movement around the room will now be more predictable, Al'ar's hit points have been reduced, and killing the Embers of Al'ar will now be both much more possible and more rewarding to the raid.
http://wowwiki.wikia.com/wiki/Patch_2.1.0

Adds: One add is summoned every time Al'ar switches position on phase I and every time he uses Rebirth in phase II. It hits for 1500 damage and has ~140.000 hp. Upon death it explodes and causes ~7000 fire damage to everyone in a ~15 yard range. Each time an add is killed on phase II, Al'ar will lose 3% of his health. 
http://wowwiki.wikia.com/wiki/Al%27ar?direction=prev&oldid=664783

**That would mean, that Solarian is buggy all over the place, since it's working with the patch 2.2 mechanics:**

The spells cast by High Astromancer Solarian have been extensively reworked. Wrath of the Astromancer is a now completely different in function. Mark of the Astromancer has been renamed to Light of the Astromancer and no longer reduces Arcane resistance. A player's Arcane Resistance now also provides normal damage mitigation to Solarian's spells.
http://wowwiki.wikia.com/wiki/Patch_2.2.0

**Comment by honeyhoney** [comment] 2016-10-16 21:00
Whilst we have used the pre-nerf mechanics for most bosses, you've correctly identified that Solarian isn't quite so similar (this is for various reasons, however, we discussed Solarian's mechanics and felt like the encounter we implemented was the most enjoyable out of the potential options). People like to through around the terms "blizzlike" and "pre-nerf", and we've clearly aspired to meet those expectations with our Tier 5 release, however we also agreed internally that this should not be at the expense of enjoyable encounters.

Seeing as Al'ar is working as intended I'll close this issue. Thanks for the report. :+1:

**Closed by honeyhoney** 2016-10-16 21:01 UTC
Labels: Core.PvE.Scripts, Dev.Report.Incomplete/Invalid

**Comment by Woomz** [comment] 2016-10-16 21:06
Yeah, well, but then there should be spawned three adds:

http://wowwiki.wikia.com/wiki/Al%27ar?direction=prev&oldid=664714 May 29th

Adds: One add is summoned every time Al'ar switches position. It hits for 1500 damage and has ~140.000 hp. Upon death it explodes and causes ~7000 fire damage to everyone in a ~15 yard range. 

http://wowwiki.wikia.com/wiki/Al%27ar?direction=prev&oldid=664701

Adds: 3 summoned every 30-60s, which hit for 1500 damage and have ~140.000 hp. Upon death they explode and cause ~7000 fire damage to everyone in a ~15 yard range.
