### ISSUE TITLE
"The Second Trial" for horde Paladins not working.

### ISSUE THREAD

**Issue by Popmycherry** [Looking4Group/L4G_Core#3530] opened 2017-04-18 17:43 UTC
Pretty much what title says. I get to where I'm supposed to go, Master Kelerun whateverface, and he has a yellow questionmark over him but I can't complete the quest.

**Comment by Saltgurka** [comment] 2017-04-18 19:21
Duplicate of https://github.com/Looking4Group/L4G_Core/issues/3417

**Closed by Saltgurka** 2017-04-18 19:21 UTC
